---
- name: Bring up docker containers
  hosts: localhost
  gather_facts: false
  vars:
    inventory:
      - name: docker_centos
        image: "chrismeyers/centos7" # centos7.4.1708  # chrismeyers/centos7
  roles:
    - { role: provision_docker, provision_docker_inventory: "{{inventory}}" }


- name: Hello world
  hosts: docker_containers
  tasks:
    - debug: 
        msg: "Hello World"