---
- hosts: all
  tasks:
    - user:
        name: ckappel
        shell: /bin/bash
        home: /home/linuxguru
        state: present

    - name: Enable Sudo
      lineinfile: dest=/etc/sudoers
                  line="ckappel ALL=(ALL) NOPASSWD{{ ":" }} ALL"
                  state=present

    - name: Set authorized key took from file
      authorized_key:
        user: ckappel
        state: present
        key: "{{ lookup('file', '/opt/ansibleuser/.ssh/ckappel/ckappel_rsa.pub') }}"
    - name: Allow publicKey Authenification
      lineinfile: dest=/etc/ssh/sshd_config
                  regexp="^PubkeyAuthentication"
                  line="PubkeyAuthentication yes"
                  state=present

    - name: Allow root SSH access
      lineinfile: dest=/etc/ssh/sshd_config
                  regexp="^PermitRootLogin"
                  line="PermitRootLogin no"
                  state=present

      notify: Restart ssh

    - user:
         name: animmervoll
         state: absent
 
